services:
  db:
    image: postgres:16
    container_name: clinix_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - clinix_db_data:/var/lib/postgresql/data

volumes:
  clinix_db_data: