"""first migration

Revision ID: 07f7360463f3
Revises: 
Create Date: 2026-03-22 00:06:25.133727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07f7360463f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=40), nullable=False),
    sa.Column('neighborhood', sa.String(length=50), nullable=False),
    sa.Column('street', sa.String(length=50), nullable=False),
    sa.Column('number', sa.String(length=10), nullable=False),
    sa.Column('complement', sa.String(length=10), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_address'))
    )
    op.create_index(op.f('ix_address_cep'), 'address', ['cep'], unique=False)
    op.create_table('entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity'))
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=30), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=1), nullable=False),
    sa.Column('author', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_logs'))
    )
    op.create_index(op.f('ix_logs_record_id'), 'logs', ['record_id'], unique=False)
    op.create_table('clinic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_name', sa.String(length=60), nullable=False),
    sa.Column('legal_name', sa.String(length=90), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], name=op.f('fk_clinic_address_id_address')),
    sa.ForeignKeyConstraint(['id'], ['entity.id'], name=op.f('fk_clinic_id_entity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinic')),
    sa.UniqueConstraint('cnpj', name=op.f('uq_clinic_cnpj')),
    sa.UniqueConstraint('legal_name', name=op.f('uq_clinic_legal_name'))
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('sex', sa.String(length=1), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], name=op.f('fk_person_address_id_address')),
    sa.ForeignKeyConstraint(['id'], ['entity.id'], name=op.f('fk_person_id_entity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person')),
    sa.UniqueConstraint('cpf', name=op.f('uq_person_cpf'))
    )
    op.create_index(op.f('ix_person_name'), 'person', ['name'], unique=False)
    op.create_table('phone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], name=op.f('fk_phone_entity_id_entity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phone'))
    )
    op.create_table('clinical_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=300), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], name=op.f('fk_clinical_access_clinic_id_clinic')),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_clinical_access_person_id_person')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinical_access')),
    sa.UniqueConstraint('clinic_id', 'person_id', name=op.f('uq_clinical_access_clinic_id')),
    sa.UniqueConstraint('email', name=op.f('uq_clinical_access_email'))
    )
    op.create_table('clinix_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=300), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_clinix_access_person_id_person')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinix_access')),
    sa.UniqueConstraint('email', name=op.f('uq_clinix_access_email')),
    sa.UniqueConstraint('person_id', name=op.f('uq_clinix_access_person_id'))
    )
    op.create_table('patient_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=300), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_patient_access_person_id_person')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_access')),
    sa.UniqueConstraint('email', name=op.f('uq_patient_access_email')),
    sa.UniqueConstraint('person_id', name=op.f('uq_patient_access_person_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_access')
    op.drop_table('clinix_access')
    op.drop_table('clinical_access')
    op.drop_table('phone')
    op.drop_index(op.f('ix_person_name'), table_name='person')
    op.drop_table('person')
    op.drop_table('clinic')
    op.drop_index(op.f('ix_logs_record_id'), table_name='logs')
    op.drop_table('logs')
    op.drop_table('entity')
    op.drop_index(op.f('ix_address_cep'), table_name='address')
    op.drop_table('address')
    # ### end Alembic commands ###
