"""add missing fk indexes composite log index
   and fix password hash length

Revision ID: 2d5fb85dc495
Revises: 07f7360463f3
Create Date: 2026-03-24 01:35:26.395112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d5fb85dc495'
down_revision: Union[str, Sequence[str], None] = '07f7360463f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_clinic_address_id'), 'clinic', ['address_id'], unique=False)
    op.create_index(op.f('ix_clinic_trade_name'), 'clinic', ['trade_name'], unique=False)
    op.alter_column('clinical_access', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.create_index(op.f('ix_clinical_access_clinic_id'), 'clinical_access', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_clinical_access_person_id'), 'clinical_access', ['person_id'], unique=False)
    op.alter_column('clinix_access', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_logs_record_id'), table_name='logs')
    op.create_index('ix_logs_table_record', 'logs', ['table_name', 'record_id'], unique=False)
    op.create_index(op.f('ix_person_address_id'), 'person', ['address_id'], unique=False)
    op.create_index(op.f('ix_phone_entity_id'), 'phone', ['entity_id'], unique=False)
    op.create_unique_constraint('uq_entity_phone', 'phone', ['entity_id', 'phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_entity_phone', 'phone', type_='unique')
    op.drop_index(op.f('ix_phone_entity_id'), table_name='phone')
    op.drop_index(op.f('ix_person_address_id'), table_name='person')
    op.drop_index('ix_logs_table_record', table_name='logs')
    op.create_index(op.f('ix_logs_record_id'), 'logs', ['record_id'], unique=False)
    op.alter_column('logs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('clinix_access', 'password_hash',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_clinical_access_person_id'), table_name='clinical_access')
    op.drop_index(op.f('ix_clinical_access_clinic_id'), table_name='clinical_access')
    op.alter_column('clinical_access', 'password_hash',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_clinic_trade_name'), table_name='clinic')
    op.drop_index(op.f('ix_clinic_address_id'), table_name='clinic')
    # ### end Alembic commands ###
