"""add appointment and docker flow

Revision ID: 57f53fce77c1
Revises: aad630c9aaeb
Create Date: 2026-05-12 19:17:50.742388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57f53fce77c1'
down_revision: Union[str, Sequence[str], None] = 'aad630c9aaeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_specialty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_clinic_id'), 'service', ['clinic_id'], unique=False)
    op.create_table('dependent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dependent_patient_id', sa.Integer(), nullable=False),
    sa.Column('guardian_patient_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dependent_patient_id'], ['patient_access.id'], ),
    sa.ForeignKeyConstraint(['guardian_patient_id'], ['patient_access.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guardian_patient_id', 'dependent_patient_id', name='uq_guardian_dependent')
    )
    op.create_index(op.f('ix_dependent_dependent_patient_id'), 'dependent', ['dependent_patient_id'], unique=False)
    op.create_index(op.f('ix_dependent_guardian_patient_id'), 'dependent', ['guardian_patient_id'], unique=False)
    op.create_table('doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinical_access_id', sa.Integer(), nullable=False),
    sa.Column('crm', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['clinical_access_id'], ['clinical_access.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinical_access_id'),
    sa.UniqueConstraint('crm')
    )
    op.create_table('doctor_schedule_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('weekdays', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_duration', sa.Integer(), nullable=False),
    sa.Column('months_ahead', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id')
    )
    op.create_table('doctor_schedule_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_schedule_slot_doctor_id'), 'doctor_schedule_slot', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_schedule_slot_start_datetime'), 'doctor_schedule_slot', ['start_datetime'], unique=False)
    op.create_index('ix_doctor_slot_datetime', 'doctor_schedule_slot', ['doctor_id', 'start_datetime'], unique=False)
    op.create_table('doctor_specialty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.ForeignKeyConstraint(['specialty_id'], ['medical_specialty.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'specialty_id', name='uq_doctor_specialty')
    )
    op.create_index(op.f('ix_doctor_specialty_doctor_id'), 'doctor_specialty', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_specialty_specialty_id'), 'doctor_specialty', ['specialty_id'], unique=False)
    op.create_table('medical_appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('clinical_access_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['clinical_access_id'], ['clinical_access.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_access.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['doctor_schedule_slot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_appointment_clinic_id'), 'medical_appointment', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_medical_appointment_clinical_access_id'), 'medical_appointment', ['clinical_access_id'], unique=False)
    op.create_index(op.f('ix_medical_appointment_doctor_id'), 'medical_appointment', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_medical_appointment_patient_id'), 'medical_appointment', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medical_appointment_service_id'), 'medical_appointment', ['service_id'], unique=False)
    op.create_index(op.f('ix_medical_appointment_slot_id'), 'medical_appointment', ['slot_id'], unique=True)
    op.alter_column('patient_access', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient_access', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_medical_appointment_slot_id'), table_name='medical_appointment')
    op.drop_index(op.f('ix_medical_appointment_service_id'), table_name='medical_appointment')
    op.drop_index(op.f('ix_medical_appointment_patient_id'), table_name='medical_appointment')
    op.drop_index(op.f('ix_medical_appointment_doctor_id'), table_name='medical_appointment')
    op.drop_index(op.f('ix_medical_appointment_clinical_access_id'), table_name='medical_appointment')
    op.drop_index(op.f('ix_medical_appointment_clinic_id'), table_name='medical_appointment')
    op.drop_table('medical_appointment')
    op.drop_index(op.f('ix_doctor_specialty_specialty_id'), table_name='doctor_specialty')
    op.drop_index(op.f('ix_doctor_specialty_doctor_id'), table_name='doctor_specialty')
    op.drop_table('doctor_specialty')
    op.drop_index('ix_doctor_slot_datetime', table_name='doctor_schedule_slot')
    op.drop_index(op.f('ix_doctor_schedule_slot_start_datetime'), table_name='doctor_schedule_slot')
    op.drop_index(op.f('ix_doctor_schedule_slot_doctor_id'), table_name='doctor_schedule_slot')
    op.drop_table('doctor_schedule_slot')
    op.drop_table('doctor_schedule_config')
    op.drop_table('doctor')
    op.drop_index(op.f('ix_dependent_guardian_patient_id'), table_name='dependent')
    op.drop_index(op.f('ix_dependent_dependent_patient_id'), table_name='dependent')
    op.drop_table('dependent')
    op.drop_index(op.f('ix_service_clinic_id'), table_name='service')
    op.drop_table('service')
    op.drop_table('medical_specialty')
    # ### end Alembic commands ###
