"""add specialty_id to service

Revision ID: 6277476c3f34
Revises: bdb2bdc3dd5d
Create Date: 2026-06-16 18:25:53.578031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6277476c3f34'
down_revision: Union[str, Sequence[str], None] = 'bdb2bdc3dd5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('specialty_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_service_specialty_id'), 'service', ['specialty_id'], unique=False)
    op.create_unique_constraint('uq_service_clinic_specialty_name', 'service', ['clinic_id', 'specialty_id', 'name'])
    op.create_foreign_key(None, 'service', 'medical_specialty', ['specialty_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service', type_='foreignkey')
    op.drop_constraint('uq_service_clinic_specialty_name', 'service', type_='unique')
    op.drop_index(op.f('ix_service_specialty_id'), table_name='service')
    op.drop_column('service', 'specialty_id')
    # ### end Alembic commands ###
