"""add patient medical record model

Revision ID: 6734567f5a2f
Revises: 6277476c3f34
Create Date: 2026-06-22 08:49:56.732210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6734567f5a2f'
down_revision: Union[str, Sequence[str], None] = '6277476c3f34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_medical_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'clinic_id', name='uq_patient_clinic_record')
    )
    op.create_index(op.f('ix_patient_medical_record_clinic_id'), 'patient_medical_record', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_patient_medical_record_patient_id'), 'patient_medical_record', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_medical_record_patient_id'), table_name='patient_medical_record')
    op.drop_index(op.f('ix_patient_medical_record_clinic_id'), table_name='patient_medical_record')
    op.drop_table('patient_medical_record')
    # ### end Alembic commands ###
