"""fix logs created_at timezone and server default

Revision ID: d7a12efcc8d0
Revises: 2d5fb85dc495
Create Date: 2026-03-24 02:06:17.462122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7a12efcc8d0'
down_revision: Union[str, Sequence[str], None] = '2d5fb85dc495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clinical_access', 'email',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.drop_constraint(op.f('uq_clinical_access_clinic_id'), 'clinical_access', type_='unique')
    op.create_unique_constraint('uq_clinic_id_person_id', 'clinical_access', ['clinic_id', 'person_id'])
    op.alter_column('clinix_access', 'email',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.create_index(op.f('ix_logs_record_id'), 'logs', ['record_id'], unique=False)
    op.alter_column('logs', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.func.now(),
               existing_nullable=False)
    op.alter_column('patient_access', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('phone', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('phone', 'type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('patient_access', 'password_hash',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_logs_record_id'), table_name='logs')
    op.alter_column('logs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DateTime(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('clinix_access', 'email',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.drop_constraint('uq_clinic_id_person_id', 'clinical_access', type_='unique')
    op.create_unique_constraint(op.f('uq_clinical_access_clinic_id'), 'clinical_access', ['clinic_id', 'person_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('clinical_access', 'email',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    # ### end Alembic commands ###
