"""add patient prescription model

Revision ID: df9f98d5cfb0
Revises: 6734567f5a2f
Create Date: 2026-06-22 10:10:26.621054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df9f98d5cfb0'
down_revision: Union[str, Sequence[str], None] = '6734567f5a2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_prescription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('prescription', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_valid', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_prescription_clinic_id'), 'patient_prescription', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_patient_prescription_doctor_id'), 'patient_prescription', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_patient_prescription_patient_id'), 'patient_prescription', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_prescription_patient_id'), table_name='patient_prescription')
    op.drop_index(op.f('ix_patient_prescription_doctor_id'), table_name='patient_prescription')
    op.drop_index(op.f('ix_patient_prescription_clinic_id'), table_name='patient_prescription')
    op.drop_table('patient_prescription')
    # ### end Alembic commands ###
