"""add patient table for patient-without-access context

Revision ID: efc4193ebd94
Revises: 57f53fce77c1
Create Date: 2026-05-28 13:41:21.733163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc4193ebd94'
down_revision: Union[str, Sequence[str], None] = '57f53fce77c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
    sa.ForeignKeyConstraint(['id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_person_id'), 'patient', ['person_id'], unique=True)
    op.drop_constraint(op.f('dependent_dependent_patient_id_fkey'), 'dependent', type_='foreignkey')
    op.drop_constraint(op.f('dependent_guardian_patient_id_fkey'), 'dependent', type_='foreignkey')
    op.create_foreign_key(None, 'dependent', 'patient', ['dependent_patient_id'], ['id'])
    op.create_foreign_key(None, 'dependent', 'patient', ['guardian_patient_id'], ['id'])
    op.drop_constraint(op.f('medical_appointment_patient_id_fkey'), 'medical_appointment', type_='foreignkey')
    op.create_foreign_key(None, 'medical_appointment', 'patient', ['patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medical_appointment', type_='foreignkey')
    op.create_foreign_key(op.f('medical_appointment_patient_id_fkey'), 'medical_appointment', 'patient_access', ['patient_id'], ['id'])
    op.drop_constraint(None, 'dependent', type_='foreignkey')
    op.drop_constraint(None, 'dependent', type_='foreignkey')
    op.create_foreign_key(op.f('dependent_guardian_patient_id_fkey'), 'dependent', 'patient_access', ['guardian_patient_id'], ['id'])
    op.create_foreign_key(op.f('dependent_dependent_patient_id_fkey'), 'dependent', 'patient_access', ['dependent_patient_id'], ['id'])
    op.drop_index(op.f('ix_patient_person_id'), table_name='patient')
    op.drop_table('patient')
    # ### end Alembic commands ###
